name: Test Swift Build

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v1

      - name: Copy preset
        run: |
          cp .swift-build-presets ~/.swift-build-presets

      - name: Checkout
        run: |
          git clone https://github.com/apple/swift.git --depth 1

      - name: Checkout dependencies
        run: |
          swift/utils/update-checkout --clone

      - name: Build
        run: |
          swift/utils/build-script --preset=hello

